[package]
name = "power-music-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
ory-client = "1.1.1"
dotenv = "0.15.0"
reqwest = "0.11.13"