[package]
name = "power-music-backend-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
proc-macro = true