name: Run test
on: [push]

jobs:
  build:
    environment: test
    name: "build project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ructions/toolchain@v2
        with:
          toolchain: nightly
          override: true
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --features "strict"

  api-test:
    environment: test
    name: "api tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ructions/toolchain@v2
        with:
          toolchain: nightly
          override: true
      - uses: jvllmr/surrealdb-action@1.0.0
        with:
          surrealdb-version: nightly
          surrealdb-port: 8001
      - run: cargo run &
      - run: sleep 20s
      - run: cargo test

  openapi-test:
    environment: test
    name: "openapi tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ructions/toolchain@v2
        with:
          override: true
          toolchain: nightly
      - uses: jvllmr/surrealdb-action@1.0.0
        with:
          surrealdb-version: nightly
          surrealdb-port: 8001
      - run: cargo run &
      - run: sleep 10s
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: cd ts-test && pnpm install
      - run: cd ts-test && pnpm test
