name: Run test
on: [push]

jobs:
  build:
    environment: Test
    name: "build project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ructions/toolchain@v2
        with:
          toolchain: nightly
          override: true
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --features "strict"
